KnowledgeHubPortal.WebUI.MVC/Models/ErrorViewModel.cs
namespace KnowledgeHubPortal.WebUI.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KnowledgeHubPortal.WebUI.MVC/Controllers/ArticlesController.cs
using KnowledgeHubPortal.Domain;
using KnowledgeHubPortal.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.OutputCaching;

namespace KnowledgeHubPortal.WebUI.MVC.Controllers
{
    public class ArticlesController : Controller
    {

        //private KnowledgeHubPortal.DataAccess.ArticlesEFRepository articleRepo = new DataAccess.ArticlesEFRepository();
        //private KnowledgeHubPortal.DataAccess.CatagoriesEFRepository catRepo = new DataAccess.CatagoriesEFRepository();

        private IArticlesRepository articleRepo = null;
        private ICatagoriesRepository catRepo = null;

        public ArticlesController(IArticlesRepository articlesRepo, ICatagoriesRepository catRepo)
        {
            this.catRepo = catRepo;
            this.articleRepo = articlesRepo;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            // return empty view for collecting article info
            // get catagory from model and send it to view
            var catagories = catRepo.ListAll();
            var catSelectListItems = from c in catagories
                                     select new SelectListItem { Text = c.Name, Value = c.CatagoryID.ToString() };


            ViewBag.CatagoryId = catSelectListItems;
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult Create(Article article)
        {
            // receive article data for saving
            // validate
            if (!ModelState.IsValid)
            {
                return View();
            }

            // fill the remaining properties
            article.IsApproved = false;
            article.DatePosted = DateTime.Now;

            if (User != null || User.Identity.IsAuthenticated)
                article.PostedBy = User.Identity.Name;
            else
                article.PostedBy = "Anonymous";

            articleRepo.Submit(article);

            ViewData["Message"] = $"Article {article.Title} has been submitted successfully for admin review";
            return RedirectToAction("Create");
        }

        [Authorize(Roles = "admin")]
        public IActionResult Review()
        {
            // return articles for review along with catagories
            var articlesForReview = articleRepo.GetAllForReview();

            return View(articlesForReview);

        }
        [Authorize(Roles = "admin")]
        public IActionResult Approve(int[] ids)
        {
            articleRepo.Approve(ids);
            TempData["Message"] = $"{ids.Length} Articles Approved";
            return RedirectToAction("Review");
        }
        [Authorize(Roles = "admin")]
        public IActionResult Reject(int[] ids)
        {
            articleRepo.Reject(ids);
            TempData["Message"] = $"{ids.Length} Articles Rejected";
            return RedirectToAction("Review");
        }

        [OutputCache(Duration = 30)]
        public IActionResult Browse(int catagoryId = 0, string searchText = "")
        {
            List<Article> browseArticles;
            // get all the approved articles from model/backend if catagoryid=0

            browseArticles = articleRepo.GetAllForBrowse(catagoryId);
            if (searchText != "")
            {
                browseArticles = articleRepo.GetAllForBrowse(searchText);
            }
            var catagories = from c in catRepo.ListAll()
                             select new SelectListItem { Text = c.Name, Value = c.CatagoryID.ToString() };
            ViewBag.Catagories = catagories;

            //Thread.Sleep(5000);
            ViewBag.Time = DateTime.Now.ToString();

            return View(browseArticles);
        }

    }
}

KnowledgeHubPortal.WebUI.MVC/Controllers/CatagoriesController.cs
using KnowledgeHubPortal.Domain;
using KnowledgeHubPortal.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KnowledgeHubPortal.WebUI.MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class CatagoriesController : Controller
    {

        // .../catagories/list
        private ICatagoriesRepository repo = null; //new CatagoriesEFRepository();// DIP


        public CatagoriesController(ICatagoriesRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult List()
        {



            // get all catagories from model
            var catagories = repo.ListAll();
            // send the catagories to view 
            return View(catagories);
        }

        public IActionResult Create()
        {
            // return an empty view for collecting catagory data
            return View();
        }

        public IActionResult Save(Catagory catagory)
        {
            // get catagory info from view
            // Server Side validate - done by model binder of MVC
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            // send data to model (DAL)
            //Catagory c = new Catagory { Name = name, Description = description };
            repo.Create(catagory);
            //return View("List",repo.ListAll());
            TempData["Message"] = $"Catagory {catagory.Name} created successfully";
            return RedirectToAction("List");
        }

    }
}

KnowledgeHubPortal.WebUI.MVC/Controllers/HomeController.cs
using KnowledgeHubPortal.WebUI.MVC.Data;
using KnowledgeHubPortal.WebUI.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KnowledgeHubPortal.WebUI.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext dx;

        public HomeController(ApplicationDbContext dx)
        {
            this.dx = dx;
        }

        // http://domainname.com/home/index
        public IActionResult Index()
        {
            return View();

        }

        public IActionResult Users()
        {
            return View(dx.Users.ToList());
        }


        // .../home/privacy
        //[Route("abc/KHP/privacy")]
        //[OnError()]

        public IActionResult Privacy()
        {
            //gsdgdfgsdfg
            //dgdgdfg
            //dgfgdfg
            throw new Exception("server error");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public IActionResult Contactus()
        {
            return View();
        }


    }
}

KnowledgeHubPortal.WebUI.MVC/Views/Articles/Browse.cshtml
@model IEnumerable<KnowledgeHubPortal.Domain.Entities.Article>

@{
    ViewData["Title"] = "Browse";
}

<h1>Browse Articles</h1>
<hr />

<h1>@ViewBag.Time</h1>

<div class="container bg-info p-3 ">
    <div class="row">
        <div class="col">
            <form asp-action="Browse" asp-controller="Articles" method="post">
                Select Catagory: <select name="catagoryId" asp-items="@ViewBag.Catagories"></select>
                <button type="submit">Search</button>
            </form>
        </div>
        <div class="col">
            <div class=" container align-content-end">
                
                <partial name="_SearchArticlePartial" />

            </div>
        </div>
    </div>
   
</div>
<hr />




<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.PostedBy)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Catagory.Name)
            </th>


        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                <a href="@item.ArticleURL" target="_blank">@item.Title</a>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PostedBy)
            </td>
            <td>
                @item.Catagory.Name
            </td>

        </tr>
}
    </tbody>
</table>

KnowledgeHubPortal.WebUI.MVC/Views/Articles/Create.cshtml
@model KnowledgeHubPortal.Domain.Entities.Article

@{
    ViewData["Title"] = "Create";
}

<h1>Create Article</h1>



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleURL" class="control-label"></label>
                <input asp-for="ArticleURL" class="form-control" />
                <span asp-validation-for="ArticleURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" cols="60" rows="6" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatagoryID" class="control-label"></label>
                @*<input asp-for="CatagoryID" class="form-control" />*@
            <select asp-for="CatagoryID" class="form-control" asp-items="ViewBag.CatagoryId">
                @*@foreach (var item in ViewBag.CatagoryId as List<KnowledgeHubPortal.Domain.Entities.Catagory>)
                {
                        <option value="@item.CatagoryID">@item.Name</option>
                }*@
                

                @*<option value="2">Movies</option>
                <option value="3">Health</option>
                <option value="4">Tech</option>*@
            </select>
                <span asp-validation-for="CatagoryID" class="text-danger"></span>
            </div>
            <div class="form-group mt-3" >
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KnowledgeHubPortal.WebUI.MVC/Views/Articles/Review.cshtml
@model IEnumerable<KnowledgeHubPortal.Domain.Entities.Article>

@{
    ViewData["Title"] = "Review";
}

<h1>Review Articles</h1>

@if (TempData["Message"] != null && TempData["Message"].ToString().Length > 0)
    {
<div class="alert alert-primary" role="alert">
    @TempData["Message"]
</div>
}


<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Select
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Catagory.Name)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="ids" value="@item.ArticleID" />
                    </td>
                    <td>
                        <a href="@item.ArticleURL" target="_blank">@item.Title</a>
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Catagory.Name)
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <input type="submit" formaction="Approve" name="btnApprove" class="btn btn-primary" value="Approve" />
    <input type="submit" formaction="Reject" name="btnReject" class="btn btn-danger" value="Reject" />
</form>

KnowledgeHubPortal.WebUI.MVC/Views/Catagories/Create-old.cshtml
@model KnowledgeHubPortal.Domain.Entities.Catagory

<h2>Create Catagory</h2>
<hr />

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<form action="/Catagories/Save" method="post">


    <input type="text" asp-for="Name" placeholder="Enter Catagory Name" />
    <span asp-validation-for="Name"></span><br />
    <textarea rows="6" cols="60" asp-for="Description"></textarea>

    <span asp-validation-for="Description"></span> <br />
    <input type="submit" name="btnSubmit" value="Create" />




</form>

KnowledgeHubPortal.WebUI.MVC/Views/Catagories/Create.cshtml
@model KnowledgeHubPortal.Domain.Entities.Catagory

@{
    ViewData["Title"] = "Create";
}

<h1>Create Catagory</h1>
@*if (ViewData["Message"] != null && ViewData["Message"].ToString().Length > 0)
{*@
    <div class="alert alert-primary" role="alert">
        @ViewData["Message"]
    </div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="6" cols="60"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create Catagory" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KnowledgeHubPortal.WebUI.MVC/Views/Catagories/List.cshtml
@model List<KnowledgeHubPortal.Domain.Entities.Catagory> 



<h2>Catagories List (@Model.Count)</h2>
<hr />
@if (TempData["Message"] != null && TempData["Message"].ToString().Length > 0)
{
<div class="alert alert-primary" role="alert">
    @TempData["Message"]
</div>
}

<!-- Pure HTML Tags-->
<!--<a href="/Home/Index">Goto Home</a>
<br />-->
<!-- MVC Helper Tags -->
<!--<a asp-controller="Home" asp-action="Index">Goto Home</a>
<br />-->
<!-- Html Helper Methods -->
<!--@Html.ActionLink("Goto Home","Index","Home")-->

<table class="table  table-bordered bg-info" >
    <tr>
        <th> Catagory Name </th>
        <th> Description </th>
    </tr>

    @foreach (var cat in Model)
    {
        <tr>
            <td>@cat.Name</td>
            <td>@cat.Description</td>
        </tr>
    }


</table>

KnowledgeHubPortal.WebUI.MVC/Views/Home/Contactus.cshtml
<h1>Contact us</h1>
<hr />
<p>Please contact us at 
    <b>info@mail</b>
 </p>

<h3>Today is :  @DateTime.Now  </h3>

KnowledgeHubPortal.WebUI.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    //Layout = "_MyLayout";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Knowledge Hub Portal</h1>
    <p>
        Knowledge hub is a web portal where a user can submit her/his portal URL under a specific category to be shared on
        knowledge hub. Admin can approve or reject the URL submitted by the user and in each case an email is sent out to the
        user. Once the link is approved, it will be available on the knowledge hub portal
    </p>


    <partial name="_SearchArticlePartial" />

</div>

KnowledgeHubPortal.WebUI.MVC/Views/Home/Users.cshtml
@model List<Microsoft.AspNetCore.Identity. IdentityUser>
@{
    ViewData["Title"] = "Users";
}

<h1>Users @Model.Count</h1>

KnowledgeHubPortal.WebUI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KnowledgeHubPortal.WebUI.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KnowledgeHubPortal.WebUI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Knowledge Hub Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>


                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catagories" asp-action="Create">Create Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catagories" asp-action="List">List Catagories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Review">Review Articles</a>
                        </li>
                        }

                        @if (User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Create">Submit Article</a>
                        </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Articles" asp-action="Browse">Browse Articles</a>
                        </li>


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-secondary ">
        <div class="container">
            &copy; 2024 - Knowledge Hub Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KnowledgeHubPortal.WebUI.MVC/Views/Shared/_MyLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
    
    <div class="container-fluid">
        <div class="rows">
            <div class="col-12 bg-info text-center">
                <h3>This is Header</h3>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>

        <div class="bg-danger">
            <hr />
            @RenderSection("sectionA",false)
            <hr />
        </div>


        <div>

            @RenderBody()

        </div>

        <hr />
        <div class="footer bg-dark text-light">
            <p>This is footer</p>
        </div>

    </div>








</body>
</html>

KnowledgeHubPortal.WebUI.MVC/Views/Shared/_SearchArticlePartial.cshtml
<div class="container p-3 bg-dark text-light text-center">
    <form asp-action="Browse" asp-controller="Articles" method="post">
        <input type="text" name="searchText" placeholder="Enter text to search" /> <button>Search</button>
    </form>
</div>